title: Rudra's Blog
description: A blog for dumping my notes and random thoughts
# baseurl: "" # No subdirectory since this is youruser.github.io
# logo:
markdown: kramdown
theme: jekyll-theme-minima  # or whatever your theme is
plugins:
  - jekyll-seo-tag

# Add this if not already present
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# Allow custom assets
include:
  - assets
