title: My GitHub Blog
description: A blog built with Jekyll and GitHub Pages
baseurl: "" # No subdirectory since this is youruser.github.io
url: "https://rudra-iitm-phd.github.io"

# Theme - pick any from https://github.com/topics/jekyll-theme
remote_theme: jekyll/minima

# # Author info (optional)
# author:
#   name: Your Name
#   email: your.email@example.com

# # Social (optional)
# social_links:
#   github: yourusername
#   twitter: yourhandle
#   linkedin: yourname

# Enable these if your theme uses them
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Markdown & highlighter
markdown: kramdown
highlighter: rouge

# Exclude these files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Build settings
future: true
lsi: false
incremental: false
